<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtSedes', 'doctrine');

/**
 * BaseSrcmtSedes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_sedes
 * @property string $sedes
 * @property string $direccion
 * @property Doctrine_Collection $SrcmtBrigadistasDado
 * @property Doctrine_Collection $SrcmtMilicianos
 * 
 * @method integer             getIdSedes()              Returns the current record's "id_sedes" value
 * @method string              getSedes()                Returns the current record's "sedes" value
 * @method string              getDireccion()            Returns the current record's "direccion" value
 * @method Doctrine_Collection getSrcmtBrigadistasDado() Returns the current record's "SrcmtBrigadistasDado" collection
 * @method Doctrine_Collection getSrcmtMilicianos()      Returns the current record's "SrcmtMilicianos" collection
 * @method SrcmtSedes          setIdSedes()              Sets the current record's "id_sedes" value
 * @method SrcmtSedes          setSedes()                Sets the current record's "sedes" value
 * @method SrcmtSedes          setDireccion()            Sets the current record's "direccion" value
 * @method SrcmtSedes          setSrcmtBrigadistasDado() Sets the current record's "SrcmtBrigadistasDado" collection
 * @method SrcmtSedes          setSrcmtMilicianos()      Sets the current record's "SrcmtMilicianos" collection
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtSedes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_sedes');
        $this->hasColumn('id_sedes', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_sedes_id_sedes',
             'length' => 4,
             ));
        $this->hasColumn('sedes', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SrcmtBrigadistasDado', array(
             'local' => 'id_sedes',
             'foreign' => 'sedes'));

        $this->hasMany('SrcmtMilicianos', array(
             'local' => 'id_sedes',
             'foreign' => 'sedes'));
    }
}