<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtParroquia', 'doctrine');

/**
 * BaseSrcmtParroquia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_parroquia
 * @property string $parroquia
 * @property integer $codigo_municipio
 * @property integer $codigo_estado
 * @property SrcmtEstado $SrcmtEstado
 * @property SrcmtMunicipio $SrcmtMunicipio
 * 
 * @method integer        getCodigoParroquia()  Returns the current record's "codigo_parroquia" value
 * @method string         getParroquia()        Returns the current record's "parroquia" value
 * @method integer        getCodigoMunicipio()  Returns the current record's "codigo_municipio" value
 * @method integer        getCodigoEstado()     Returns the current record's "codigo_estado" value
 * @method SrcmtEstado    getSrcmtEstado()      Returns the current record's "SrcmtEstado" value
 * @method SrcmtMunicipio getSrcmtMunicipio()   Returns the current record's "SrcmtMunicipio" value
 * @method SrcmtParroquia setCodigoParroquia()  Sets the current record's "codigo_parroquia" value
 * @method SrcmtParroquia setParroquia()        Sets the current record's "parroquia" value
 * @method SrcmtParroquia setCodigoMunicipio()  Sets the current record's "codigo_municipio" value
 * @method SrcmtParroquia setCodigoEstado()     Sets the current record's "codigo_estado" value
 * @method SrcmtParroquia setSrcmtEstado()      Sets the current record's "SrcmtEstado" value
 * @method SrcmtParroquia setSrcmtMunicipio()   Sets the current record's "SrcmtMunicipio" value
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtParroquia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_parroquia');
        $this->hasColumn('codigo_parroquia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('parroquia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codigo_municipio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SrcmtEstado', array(
             'local' => 'codigo_estado',
             'foreign' => 'codigo_estado'));

        $this->hasOne('SrcmtMunicipio', array(
             'local' => array(
             0 => 'codigo_estado',
             1 => 'codigo_municipio',
             ),
             'foreign' => array(
             0 => 'codigo_estado',
             1 => 'codigo_municipio',
             )));
    }
}