<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtBrigadistasDado', 'doctrine');

/**
 * BaseSrcmtBrigadistasDado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_brigadista
 * @property enum $nacionalidad
 * @property integer $cedula_identidad
 * @property string $religion
 * @property string $primer_apellido
 * @property string $segundo_apellido
 * @property string $primer_nombre
 * @property string $segundo_nombre
 * @property enum $sexo
 * @property date $fecha_nacimiento
 * @property string $lugar_de_nacimiento
 * @property enum $estado_civil
 * @property string $foto
 * @property enum $grupo_sanguineo
 * @property integer $codigo_estado
 * @property integer $codigo_municipio
 * @property integer $codigo_parroquia
 * @property integer $codigo_ciudad
 * @property string $direccion_domiciliaria
 * @property string $telefono_domicilio
 * @property string $telefono_movil
 * @property string $correo_electronico
 * @property string $direccion_emergencia
 * @property string $telefono_emergencia
 * @property string $unidad_adscripcion_laboral
 * @property string $extension_interna
 * @property enum $perfil_empleado
 * @property string $jefe_sector
 * @property enum $grado_instruccion
 * @property string $especialidad
 * @property integer $sedes
 * @property string $jerarquia
 * @property string $profesion
 * @property string $oficio
 * @property string $centro_votacion_cne
 * @property string $direccion_oficina
 * @property string $talla_pantalon
 * @property string $talla_camisa
 * @property string $talla_calzado
 * @property string $talla_gorra
 * @property string $estatura
 * @property float $peso
 * @property string $color_cabello
 * @property string $color_piel
 * @property string $discapacidad
 * @property string $alergias
 * @property enum $dominio_mano
 * @property string $deporte
 * @property string $actividades_culturales
 * @property string $apellidos_beneficiario
 * @property string $nombres_beneficiario
 * @property string $cedula_beneficiario
 * @property string $telefono_beneficiario
 * @property SrcmtSedes $SrcmtSedes
 * @property Doctrine_Collection $actividad_academica
 * @property Doctrine_Collection $actividad_icm
 * @property Doctrine_Collection $SrcmtActividadAcademicaBrigadistaDado
 * @property Doctrine_Collection $SrcmtActividadIcmBrigadistaDado
 * 
 * @method integer              getCodigoBrigadista()                      Returns the current record's "codigo_brigadista" value
 * @method enum                 getNacionalidad()                          Returns the current record's "nacionalidad" value
 * @method integer              getCedulaIdentidad()                       Returns the current record's "cedula_identidad" value
 * @method string               getReligion()                              Returns the current record's "religion" value
 * @method string               getPrimerApellido()                        Returns the current record's "primer_apellido" value
 * @method string               getSegundoApellido()                       Returns the current record's "segundo_apellido" value
 * @method string               getPrimerNombre()                          Returns the current record's "primer_nombre" value
 * @method string               getSegundoNombre()                         Returns the current record's "segundo_nombre" value
 * @method enum                 getSexo()                                  Returns the current record's "sexo" value
 * @method date                 getFechaNacimiento()                       Returns the current record's "fecha_nacimiento" value
 * @method string               getLugarDeNacimiento()                     Returns the current record's "lugar_de_nacimiento" value
 * @method enum                 getEstadoCivil()                           Returns the current record's "estado_civil" value
 * @method string               getFoto()                                  Returns the current record's "foto" value
 * @method enum                 getGrupoSanguineo()                        Returns the current record's "grupo_sanguineo" value
 * @method integer              getCodigoEstado()                          Returns the current record's "codigo_estado" value
 * @method integer              getCodigoMunicipio()                       Returns the current record's "codigo_municipio" value
 * @method integer              getCodigoParroquia()                       Returns the current record's "codigo_parroquia" value
 * @method integer              getCodigoCiudad()                          Returns the current record's "codigo_ciudad" value
 * @method string               getDireccionDomiciliaria()                 Returns the current record's "direccion_domiciliaria" value
 * @method string               getTelefonoDomicilio()                     Returns the current record's "telefono_domicilio" value
 * @method string               getTelefonoMovil()                         Returns the current record's "telefono_movil" value
 * @method string               getCorreoElectronico()                     Returns the current record's "correo_electronico" value
 * @method string               getDireccionEmergencia()                   Returns the current record's "direccion_emergencia" value
 * @method string               getTelefonoEmergencia()                    Returns the current record's "telefono_emergencia" value
 * @method string               getUnidadAdscripcionLaboral()              Returns the current record's "unidad_adscripcion_laboral" value
 * @method string               getExtensionInterna()                      Returns the current record's "extension_interna" value
 * @method enum                 getPerfilEmpleado()                        Returns the current record's "perfil_empleado" value
 * @method string               getJefeSector()                            Returns the current record's "jefe_sector" value
 * @method enum                 getGradoInstruccion()                      Returns the current record's "grado_instruccion" value
 * @method string               getEspecialidad()                          Returns the current record's "especialidad" value
 * @method integer              getSedes()                                 Returns the current record's "sedes" value
 * @method string               getJerarquia()                             Returns the current record's "jerarquia" value
 * @method string               getProfesion()                             Returns the current record's "profesion" value
 * @method string               getOficio()                                Returns the current record's "oficio" value
 * @method string               getCentroVotacionCne()                     Returns the current record's "centro_votacion_cne" value
 * @method string               getDireccionOficina()                      Returns the current record's "direccion_oficina" value
 * @method string               getTallaPantalon()                         Returns the current record's "talla_pantalon" value
 * @method string               getTallaCamisa()                           Returns the current record's "talla_camisa" value
 * @method string               getTallaCalzado()                          Returns the current record's "talla_calzado" value
 * @method string               getTallaGorra()                            Returns the current record's "talla_gorra" value
 * @method string               getEstatura()                              Returns the current record's "estatura" value
 * @method float                getPeso()                                  Returns the current record's "peso" value
 * @method string               getColorCabello()                          Returns the current record's "color_cabello" value
 * @method string               getColorPiel()                             Returns the current record's "color_piel" value
 * @method string               getDiscapacidad()                          Returns the current record's "discapacidad" value
 * @method string               getAlergias()                              Returns the current record's "alergias" value
 * @method enum                 getDominioMano()                           Returns the current record's "dominio_mano" value
 * @method string               getDeporte()                               Returns the current record's "deporte" value
 * @method string               getActividadesCulturales()                 Returns the current record's "actividades_culturales" value
 * @method string               getApellidosBeneficiario()                 Returns the current record's "apellidos_beneficiario" value
 * @method string               getNombresBeneficiario()                   Returns the current record's "nombres_beneficiario" value
 * @method string               getCedulaBeneficiario()                    Returns the current record's "cedula_beneficiario" value
 * @method string               getTelefonoBeneficiario()                  Returns the current record's "telefono_beneficiario" value
 * @method SrcmtSedes           getSrcmtSedes()                            Returns the current record's "SrcmtSedes" value
 * @method Doctrine_Collection  getActividadAcademica()                    Returns the current record's "actividad_academica" collection
 * @method Doctrine_Collection  getActividadIcm()                          Returns the current record's "actividad_icm" collection
 * @method Doctrine_Collection  getSrcmtActividadAcademicaBrigadistaDado() Returns the current record's "SrcmtActividadAcademicaBrigadistaDado" collection
 * @method Doctrine_Collection  getSrcmtActividadIcmBrigadistaDado()       Returns the current record's "SrcmtActividadIcmBrigadistaDado" collection
 * @method SrcmtBrigadistasDado setCodigoBrigadista()                      Sets the current record's "codigo_brigadista" value
 * @method SrcmtBrigadistasDado setNacionalidad()                          Sets the current record's "nacionalidad" value
 * @method SrcmtBrigadistasDado setCedulaIdentidad()                       Sets the current record's "cedula_identidad" value
 * @method SrcmtBrigadistasDado setReligion()                              Sets the current record's "religion" value
 * @method SrcmtBrigadistasDado setPrimerApellido()                        Sets the current record's "primer_apellido" value
 * @method SrcmtBrigadistasDado setSegundoApellido()                       Sets the current record's "segundo_apellido" value
 * @method SrcmtBrigadistasDado setPrimerNombre()                          Sets the current record's "primer_nombre" value
 * @method SrcmtBrigadistasDado setSegundoNombre()                         Sets the current record's "segundo_nombre" value
 * @method SrcmtBrigadistasDado setSexo()                                  Sets the current record's "sexo" value
 * @method SrcmtBrigadistasDado setFechaNacimiento()                       Sets the current record's "fecha_nacimiento" value
 * @method SrcmtBrigadistasDado setLugarDeNacimiento()                     Sets the current record's "lugar_de_nacimiento" value
 * @method SrcmtBrigadistasDado setEstadoCivil()                           Sets the current record's "estado_civil" value
 * @method SrcmtBrigadistasDado setFoto()                                  Sets the current record's "foto" value
 * @method SrcmtBrigadistasDado setGrupoSanguineo()                        Sets the current record's "grupo_sanguineo" value
 * @method SrcmtBrigadistasDado setCodigoEstado()                          Sets the current record's "codigo_estado" value
 * @method SrcmtBrigadistasDado setCodigoMunicipio()                       Sets the current record's "codigo_municipio" value
 * @method SrcmtBrigadistasDado setCodigoParroquia()                       Sets the current record's "codigo_parroquia" value
 * @method SrcmtBrigadistasDado setCodigoCiudad()                          Sets the current record's "codigo_ciudad" value
 * @method SrcmtBrigadistasDado setDireccionDomiciliaria()                 Sets the current record's "direccion_domiciliaria" value
 * @method SrcmtBrigadistasDado setTelefonoDomicilio()                     Sets the current record's "telefono_domicilio" value
 * @method SrcmtBrigadistasDado setTelefonoMovil()                         Sets the current record's "telefono_movil" value
 * @method SrcmtBrigadistasDado setCorreoElectronico()                     Sets the current record's "correo_electronico" value
 * @method SrcmtBrigadistasDado setDireccionEmergencia()                   Sets the current record's "direccion_emergencia" value
 * @method SrcmtBrigadistasDado setTelefonoEmergencia()                    Sets the current record's "telefono_emergencia" value
 * @method SrcmtBrigadistasDado setUnidadAdscripcionLaboral()              Sets the current record's "unidad_adscripcion_laboral" value
 * @method SrcmtBrigadistasDado setExtensionInterna()                      Sets the current record's "extension_interna" value
 * @method SrcmtBrigadistasDado setPerfilEmpleado()                        Sets the current record's "perfil_empleado" value
 * @method SrcmtBrigadistasDado setJefeSector()                            Sets the current record's "jefe_sector" value
 * @method SrcmtBrigadistasDado setGradoInstruccion()                      Sets the current record's "grado_instruccion" value
 * @method SrcmtBrigadistasDado setEspecialidad()                          Sets the current record's "especialidad" value
 * @method SrcmtBrigadistasDado setSedes()                                 Sets the current record's "sedes" value
 * @method SrcmtBrigadistasDado setJerarquia()                             Sets the current record's "jerarquia" value
 * @method SrcmtBrigadistasDado setProfesion()                             Sets the current record's "profesion" value
 * @method SrcmtBrigadistasDado setOficio()                                Sets the current record's "oficio" value
 * @method SrcmtBrigadistasDado setCentroVotacionCne()                     Sets the current record's "centro_votacion_cne" value
 * @method SrcmtBrigadistasDado setDireccionOficina()                      Sets the current record's "direccion_oficina" value
 * @method SrcmtBrigadistasDado setTallaPantalon()                         Sets the current record's "talla_pantalon" value
 * @method SrcmtBrigadistasDado setTallaCamisa()                           Sets the current record's "talla_camisa" value
 * @method SrcmtBrigadistasDado setTallaCalzado()                          Sets the current record's "talla_calzado" value
 * @method SrcmtBrigadistasDado setTallaGorra()                            Sets the current record's "talla_gorra" value
 * @method SrcmtBrigadistasDado setEstatura()                              Sets the current record's "estatura" value
 * @method SrcmtBrigadistasDado setPeso()                                  Sets the current record's "peso" value
 * @method SrcmtBrigadistasDado setColorCabello()                          Sets the current record's "color_cabello" value
 * @method SrcmtBrigadistasDado setColorPiel()                             Sets the current record's "color_piel" value
 * @method SrcmtBrigadistasDado setDiscapacidad()                          Sets the current record's "discapacidad" value
 * @method SrcmtBrigadistasDado setAlergias()                              Sets the current record's "alergias" value
 * @method SrcmtBrigadistasDado setDominioMano()                           Sets the current record's "dominio_mano" value
 * @method SrcmtBrigadistasDado setDeporte()                               Sets the current record's "deporte" value
 * @method SrcmtBrigadistasDado setActividadesCulturales()                 Sets the current record's "actividades_culturales" value
 * @method SrcmtBrigadistasDado setApellidosBeneficiario()                 Sets the current record's "apellidos_beneficiario" value
 * @method SrcmtBrigadistasDado setNombresBeneficiario()                   Sets the current record's "nombres_beneficiario" value
 * @method SrcmtBrigadistasDado setCedulaBeneficiario()                    Sets the current record's "cedula_beneficiario" value
 * @method SrcmtBrigadistasDado setTelefonoBeneficiario()                  Sets the current record's "telefono_beneficiario" value
 * @method SrcmtBrigadistasDado setSrcmtSedes()                            Sets the current record's "SrcmtSedes" value
 * @method SrcmtBrigadistasDado setActividadAcademica()                    Sets the current record's "actividad_academica" collection
 * @method SrcmtBrigadistasDado setActividadIcm()                          Sets the current record's "actividad_icm" collection
 * @method SrcmtBrigadistasDado setSrcmtActividadAcademicaBrigadistaDado() Sets the current record's "SrcmtActividadAcademicaBrigadistaDado" collection
 * @method SrcmtBrigadistasDado setSrcmtActividadIcmBrigadistaDado()       Sets the current record's "SrcmtActividadIcmBrigadistaDado" collection
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtBrigadistasDado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_brigadistas_dado');
        $this->hasColumn('codigo_brigadista', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_brigadistas_dado_codigo_brigadista',
             'length' => 4,
             ));
        $this->hasColumn('nacionalidad', 'enum', 1, array(
             'type' => 'enum',
             'length' => 1,
             'values' => 
             array(
              0 => 'V',
              1 => 'E',
             ),
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('cedula_identidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'unique' => true,
             'length' => 4,
             ));
        $this->hasColumn('religion', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('primer_apellido', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('segundo_apellido', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('primer_nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('segundo_nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('sexo', 'enum', 1, array(
             'type' => 'enum',
             'length' => 1,
             'values' => 
             array(
              0 => 'F',
              1 => 'M',
             ),
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('lugar_de_nacimiento', 'string', 40, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 40,
             ));
        $this->hasColumn('estado_civil', 'enum', 11, array(
             'type' => 'enum',
             'length' => 11,
             'values' => 
             array(
              0 => 'SOLTERO',
              1 => 'CASADO',
              2 => 'DIVORCIADO',
              3 => 'VIUDO',
              4 => 'CONCUBINATO',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('foto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('grupo_sanguineo', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'O+',
              1 => 'O-',
              2 => 'A-',
              3 => 'A+',
              4 => 'B-',
              5 => 'B+',
              6 => 'AB-',
              7 => 'AB+',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('codigo_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_municipio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_parroquia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_ciudad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('direccion_domiciliaria', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_domicilio', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('telefono_movil', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('correo_electronico', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('direccion_emergencia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_emergencia', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('unidad_adscripcion_laboral', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('extension_interna', 'string', 6, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 6,
             ));
        $this->hasColumn('perfil_empleado', 'enum', 14, array(
             'type' => 'enum',
             'length' => 14,
             'values' => 
             array(
              0 => '',
              1 => 'Directivo',
              2 => 'Administrativo',
              3 => 'Docente',
              4 => 'Obrero',
             ),
             'default' => '',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('jefe_sector', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('grado_instruccion', 'enum', 14, array(
             'type' => 'enum',
             'length' => 14,
             'values' => 
             array(
              0 => '',
              1 => 'Basico',
              2 => 'Medio',
              3 => 'Diversificado',
              4 => 'Universitario',
              5 => 'Posgrado',
              6 => 'Doctorado',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('especialidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sedes', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('jerarquia', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('profesion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('oficio', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('centro_votacion_cne', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('direccion_oficina', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('talla_pantalon', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('talla_camisa', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('talla_calzado', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('talla_gorra', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('estatura', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('peso', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('color_cabello', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 10,
             ));
        $this->hasColumn('color_piel', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('discapacidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('alergias', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('dominio_mano', 'enum', 15, array(
             'type' => 'enum',
             'length' => 15,
             'values' => 
             array(
              0 => '',
              1 => 'Diestro',
              2 => 'Siniestro',
              3 => 'Ambidiestro',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('deporte', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('actividades_culturales', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('apellidos_beneficiario', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 60,
             ));
        $this->hasColumn('nombres_beneficiario', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 60,
             ));
        $this->hasColumn('cedula_beneficiario', 'string', 11, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 11,
             ));
        $this->hasColumn('telefono_beneficiario', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SrcmtSedes', array(
             'local' => 'sedes',
             'foreign' => 'id_sedes'));

        $this->hasMany('SrcmtActividadesAcademicas as actividad_academica', array(
             'refClass' => 'SrcmtActividadAcademicaBrigadistaDado',
             'local' => 'codigo_brigadista',
             'foreign' => 'codigo_actividad_academica'));

        $this->hasMany('SrcmtActividadesIcm as actividad_icm', array(
             'refClass' => 'SrcmtActividadIcmBrigadistaDado',
             'local' => 'codigo_brigadista',
             'foreign' => 'codigo_actividad'));

        $this->hasMany('SrcmtActividadAcademicaBrigadistaDado', array(
             'local' => 'codigo_brigadista',
             'foreign' => 'codigo_brigadista'));

        $this->hasMany('SrcmtActividadIcmBrigadistaDado', array(
             'local' => 'codigo_brigadista',
             'foreign' => 'codigo_brigadista'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}