<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtActividadIcmBrigadistaDado', 'doctrine');

/**
 * BaseSrcmtActividadIcmBrigadistaDado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $codigo_brigadista
 * @property integer $codigo_actividad
 * @property SrcmtActividadesIcm $SrcmtActividadesIcm
 * @property SrcmtBrigadistasDado $SrcmtBrigadistasDado
 * 
 * @method integer                         getId()                   Returns the current record's "id" value
 * @method integer                         getCodigoBrigadista()     Returns the current record's "codigo_brigadista" value
 * @method integer                         getCodigoActividad()      Returns the current record's "codigo_actividad" value
 * @method SrcmtActividadesIcm             getSrcmtActividadesIcm()  Returns the current record's "SrcmtActividadesIcm" value
 * @method SrcmtBrigadistasDado            getSrcmtBrigadistasDado() Returns the current record's "SrcmtBrigadistasDado" value
 * @method SrcmtActividadIcmBrigadistaDado setId()                   Sets the current record's "id" value
 * @method SrcmtActividadIcmBrigadistaDado setCodigoBrigadista()     Sets the current record's "codigo_brigadista" value
 * @method SrcmtActividadIcmBrigadistaDado setCodigoActividad()      Sets the current record's "codigo_actividad" value
 * @method SrcmtActividadIcmBrigadistaDado setSrcmtActividadesIcm()  Sets the current record's "SrcmtActividadesIcm" value
 * @method SrcmtActividadIcmBrigadistaDado setSrcmtBrigadistasDado() Sets the current record's "SrcmtBrigadistasDado" value
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtActividadIcmBrigadistaDado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_actividad_icm_brigadista_dado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_actividad_icm_brigadista_dado_id',
             'length' => 4,
             ));
        $this->hasColumn('codigo_brigadista', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_actividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SrcmtActividadesIcm', array(
             'local' => 'codigo_actividad',
             'foreign' => 'codigo_actividad_icm'));

        $this->hasOne('SrcmtBrigadistasDado', array(
             'local' => 'codigo_brigadista',
             'foreign' => 'codigo_brigadista'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}