<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtCiudad', 'doctrine');

/**
 * BaseSrcmtCiudad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_ciudad
 * @property integer $codigo_estado
 * @property integer $codigo_municipio
 * @property string $ciudad
 * @property SrcmtEstado $SrcmtEstado
 * @property SrcmtMunicipio $SrcmtMunicipio
 * 
 * @method integer        getCodigoCiudad()     Returns the current record's "codigo_ciudad" value
 * @method integer        getCodigoEstado()     Returns the current record's "codigo_estado" value
 * @method integer        getCodigoMunicipio()  Returns the current record's "codigo_municipio" value
 * @method string         getCiudad()           Returns the current record's "ciudad" value
 * @method SrcmtEstado    getSrcmtEstado()      Returns the current record's "SrcmtEstado" value
 * @method SrcmtMunicipio getSrcmtMunicipio()   Returns the current record's "SrcmtMunicipio" value
 * @method SrcmtCiudad    setCodigoCiudad()     Sets the current record's "codigo_ciudad" value
 * @method SrcmtCiudad    setCodigoEstado()     Sets the current record's "codigo_estado" value
 * @method SrcmtCiudad    setCodigoMunicipio()  Sets the current record's "codigo_municipio" value
 * @method SrcmtCiudad    setCiudad()           Sets the current record's "ciudad" value
 * @method SrcmtCiudad    setSrcmtEstado()      Sets the current record's "SrcmtEstado" value
 * @method SrcmtCiudad    setSrcmtMunicipio()   Sets the current record's "SrcmtMunicipio" value
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtCiudad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_ciudad');
        $this->hasColumn('codigo_ciudad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo_municipio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('ciudad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SrcmtEstado', array(
             'local' => 'codigo_estado',
             'foreign' => 'codigo_estado'));

        $this->hasOne('SrcmtMunicipio', array(
             'local' => array(
             0 => 'codigo_estado',
             1 => 'codigo_municipio',
             ),
             'foreign' => array(
             0 => 'codigo_estado',
             1 => 'codigo_municipio',
             )));
    }
}