<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtActividadAcademicaMiliciano', 'doctrine');

/**
 * BaseSrcmtActividadAcademicaMiliciano
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $codigo_miliciano
 * @property integer $codigo_actividad_academica
 * @property SrcmtActividadesAcademicas $SrcmtActividadesAcademicas
 * @property SrcmtMilicianos $SrcmtMilicianos
 * 
 * @method integer                          getId()                         Returns the current record's "id" value
 * @method integer                          getCodigoMiliciano()            Returns the current record's "codigo_miliciano" value
 * @method integer                          getCodigoActividadAcademica()   Returns the current record's "codigo_actividad_academica" value
 * @method SrcmtActividadesAcademicas       getSrcmtActividadesAcademicas() Returns the current record's "SrcmtActividadesAcademicas" value
 * @method SrcmtMilicianos                  getSrcmtMilicianos()            Returns the current record's "SrcmtMilicianos" value
 * @method SrcmtActividadAcademicaMiliciano setId()                         Sets the current record's "id" value
 * @method SrcmtActividadAcademicaMiliciano setCodigoMiliciano()            Sets the current record's "codigo_miliciano" value
 * @method SrcmtActividadAcademicaMiliciano setCodigoActividadAcademica()   Sets the current record's "codigo_actividad_academica" value
 * @method SrcmtActividadAcademicaMiliciano setSrcmtActividadesAcademicas() Sets the current record's "SrcmtActividadesAcademicas" value
 * @method SrcmtActividadAcademicaMiliciano setSrcmtMilicianos()            Sets the current record's "SrcmtMilicianos" value
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtActividadAcademicaMiliciano extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_actividad_academica_miliciano');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_actividad_academica_miliciano_id',
             'length' => 4,
             ));
        $this->hasColumn('codigo_miliciano', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_actividad_academica', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SrcmtActividadesAcademicas', array(
             'local' => 'codigo_actividad_academica',
             'foreign' => 'codigo_actividad_academica'));

        $this->hasOne('SrcmtMilicianos', array(
             'local' => 'codigo_miliciano',
             'foreign' => 'codigo_miliciano'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}