<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtPfg', 'doctrine');

/**
 * BaseSrcmtPfg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pfg
 * @property string $pfg
 * @property Doctrine_Collection $SrcmtMilicianos
 * 
 * @method integer             getIdPfg()           Returns the current record's "id_pfg" value
 * @method string              getPfg()             Returns the current record's "pfg" value
 * @method Doctrine_Collection getSrcmtMilicianos() Returns the current record's "SrcmtMilicianos" collection
 * @method SrcmtPfg            setIdPfg()           Sets the current record's "id_pfg" value
 * @method SrcmtPfg            setPfg()             Sets the current record's "pfg" value
 * @method SrcmtPfg            setSrcmtMilicianos() Sets the current record's "SrcmtMilicianos" collection
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtPfg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_pfg');
        $this->hasColumn('id_pfg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_pfg_id_pfg',
             'length' => 4,
             ));
        $this->hasColumn('pfg', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SrcmtMilicianos', array(
             'local' => 'id_pfg',
             'foreign' => 'programa_formacion_grado'));
    }
}