<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtEstado', 'doctrine');

/**
 * BaseSrcmtEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_estado
 * @property string $estado
 * @property Doctrine_Collection $SrcmtMunicipio
 * @property SrcmtCiudad $SrcmtCiudad
 * @property SrcmtParroquia $SrcmtParroquia
 * 
 * @method integer             getCodigoEstado()   Returns the current record's "codigo_estado" value
 * @method string              getEstado()         Returns the current record's "estado" value
 * @method Doctrine_Collection getSrcmtMunicipio() Returns the current record's "SrcmtMunicipio" collection
 * @method SrcmtCiudad         getSrcmtCiudad()    Returns the current record's "SrcmtCiudad" value
 * @method SrcmtParroquia      getSrcmtParroquia() Returns the current record's "SrcmtParroquia" value
 * @method SrcmtEstado         setCodigoEstado()   Sets the current record's "codigo_estado" value
 * @method SrcmtEstado         setEstado()         Sets the current record's "estado" value
 * @method SrcmtEstado         setSrcmtMunicipio() Sets the current record's "SrcmtMunicipio" collection
 * @method SrcmtEstado         setSrcmtCiudad()    Sets the current record's "SrcmtCiudad" value
 * @method SrcmtEstado         setSrcmtParroquia() Sets the current record's "SrcmtParroquia" value
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_estado');
        $this->hasColumn('codigo_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SrcmtMunicipio', array(
             'local' => 'codigo_estado',
             'foreign' => 'codigo_estado'));

        $this->hasOne('SrcmtCiudad', array(
             'local' => 'codigo_estado',
             'foreign' => 'codigo_estado'));

        $this->hasOne('SrcmtParroquia', array(
             'local' => 'codigo_estado',
             'foreign' => 'codigo_estado'));
    }
}