<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtActividadesIcm', 'doctrine');

/**
 * BaseSrcmtActividadesIcm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_actividad_icm
 * @property integer $codigo_tipo_actividad
 * @property string $actividad
 * @property string $responsable
 * @property date $fecha
 * @property string $lugar
 * @property string $duracion
 * @property string $descripcion
 * @property SrcmtTipoActividad $SrcmtTipoActividad
 * @property Doctrine_Collection $milicianos
 * @property Doctrine_Collection $brigadistas_dado
 * @property Doctrine_Collection $SrcmtActividadIcmBrigadistaDado
 * @property Doctrine_Collection $SrcmtActividadIcmMiliciano
 * 
 * @method integer             getCodigoActividadIcm()              Returns the current record's "codigo_actividad_icm" value
 * @method integer             getCodigoTipoActividad()             Returns the current record's "codigo_tipo_actividad" value
 * @method string              getActividad()                       Returns the current record's "actividad" value
 * @method string              getResponsable()                     Returns the current record's "responsable" value
 * @method date                getFecha()                           Returns the current record's "fecha" value
 * @method string              getLugar()                           Returns the current record's "lugar" value
 * @method string              getDuracion()                        Returns the current record's "duracion" value
 * @method string              getDescripcion()                     Returns the current record's "descripcion" value
 * @method SrcmtTipoActividad  getSrcmtTipoActividad()              Returns the current record's "SrcmtTipoActividad" value
 * @method Doctrine_Collection getMilicianos()                      Returns the current record's "milicianos" collection
 * @method Doctrine_Collection getBrigadistasDado()                 Returns the current record's "brigadistas_dado" collection
 * @method Doctrine_Collection getSrcmtActividadIcmBrigadistaDado() Returns the current record's "SrcmtActividadIcmBrigadistaDado" collection
 * @method Doctrine_Collection getSrcmtActividadIcmMiliciano()      Returns the current record's "SrcmtActividadIcmMiliciano" collection
 * @method SrcmtActividadesIcm setCodigoActividadIcm()              Sets the current record's "codigo_actividad_icm" value
 * @method SrcmtActividadesIcm setCodigoTipoActividad()             Sets the current record's "codigo_tipo_actividad" value
 * @method SrcmtActividadesIcm setActividad()                       Sets the current record's "actividad" value
 * @method SrcmtActividadesIcm setResponsable()                     Sets the current record's "responsable" value
 * @method SrcmtActividadesIcm setFecha()                           Sets the current record's "fecha" value
 * @method SrcmtActividadesIcm setLugar()                           Sets the current record's "lugar" value
 * @method SrcmtActividadesIcm setDuracion()                        Sets the current record's "duracion" value
 * @method SrcmtActividadesIcm setDescripcion()                     Sets the current record's "descripcion" value
 * @method SrcmtActividadesIcm setSrcmtTipoActividad()              Sets the current record's "SrcmtTipoActividad" value
 * @method SrcmtActividadesIcm setMilicianos()                      Sets the current record's "milicianos" collection
 * @method SrcmtActividadesIcm setBrigadistasDado()                 Sets the current record's "brigadistas_dado" collection
 * @method SrcmtActividadesIcm setSrcmtActividadIcmBrigadistaDado() Sets the current record's "SrcmtActividadIcmBrigadistaDado" collection
 * @method SrcmtActividadesIcm setSrcmtActividadIcmMiliciano()      Sets the current record's "SrcmtActividadIcmMiliciano" collection
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtActividadesIcm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_actividades_icm');
        $this->hasColumn('codigo_actividad_icm', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_actividades_icm_codigo_actividad_icm',
             'length' => 4,
             ));
        $this->hasColumn('codigo_tipo_actividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('actividad', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('responsable', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('lugar', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('duracion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SrcmtTipoActividad', array(
             'local' => 'codigo_tipo_actividad',
             'foreign' => 'codigo_tipo_actividad'));

        $this->hasMany('SrcmtMilicianos as milicianos', array(
             'refClass' => 'SrcmtActividadIcmMiliciano',
             'local' => 'codigo_actividad',
             'foreign' => 'codigo_miliciano'));

        $this->hasMany('SrcmtBrigadistasDado as brigadistas_dado', array(
             'refClass' => 'SrcmtActividadIcmBrigadistaDado',
             'local' => 'codigo_actividad',
             'foreign' => 'codigo_brigadista'));

        $this->hasMany('SrcmtActividadIcmBrigadistaDado', array(
             'local' => 'codigo_actividad_icm',
             'foreign' => 'codigo_actividad'));

        $this->hasMany('SrcmtActividadIcmMiliciano', array(
             'local' => 'codigo_actividad_icm',
             'foreign' => 'codigo_actividad'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}