<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtTipoActividad', 'doctrine');

/**
 * BaseSrcmtTipoActividad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_tipo_actividad
 * @property string $tipo_actividad
 * @property Doctrine_Collection $SrcmtActividadesAcademicas
 * @property Doctrine_Collection $SrcmtActividadesIcm
 * 
 * @method integer             getCodigoTipoActividad()        Returns the current record's "codigo_tipo_actividad" value
 * @method string              getTipoActividad()              Returns the current record's "tipo_actividad" value
 * @method Doctrine_Collection getSrcmtActividadesAcademicas() Returns the current record's "SrcmtActividadesAcademicas" collection
 * @method Doctrine_Collection getSrcmtActividadesIcm()        Returns the current record's "SrcmtActividadesIcm" collection
 * @method SrcmtTipoActividad  setCodigoTipoActividad()        Sets the current record's "codigo_tipo_actividad" value
 * @method SrcmtTipoActividad  setTipoActividad()              Sets the current record's "tipo_actividad" value
 * @method SrcmtTipoActividad  setSrcmtActividadesAcademicas() Sets the current record's "SrcmtActividadesAcademicas" collection
 * @method SrcmtTipoActividad  setSrcmtActividadesIcm()        Sets the current record's "SrcmtActividadesIcm" collection
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtTipoActividad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_tipo_actividad');
        $this->hasColumn('codigo_tipo_actividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_tipo_actividad_codigo_tipo_actividad',
             'length' => 4,
             ));
        $this->hasColumn('tipo_actividad', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SrcmtActividadesAcademicas', array(
             'local' => 'codigo_tipo_actividad',
             'foreign' => 'codigo_tipo_actividad'));

        $this->hasMany('SrcmtActividadesIcm', array(
             'local' => 'codigo_tipo_actividad',
             'foreign' => 'codigo_tipo_actividad'));
    }
}