<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtActividadIcmMiliciano', 'doctrine');

/**
 * BaseSrcmtActividadIcmMiliciano
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $codigo_miliciano
 * @property integer $codigo_actividad
 * @property SrcmtActividadesIcm $SrcmtActividadesIcm
 * @property SrcmtMilicianos $SrcmtMilicianos
 * 
 * @method integer                    getId()                  Returns the current record's "id" value
 * @method integer                    getCodigoMiliciano()     Returns the current record's "codigo_miliciano" value
 * @method integer                    getCodigoActividad()     Returns the current record's "codigo_actividad" value
 * @method SrcmtActividadesIcm        getSrcmtActividadesIcm() Returns the current record's "SrcmtActividadesIcm" value
 * @method SrcmtMilicianos            getSrcmtMilicianos()     Returns the current record's "SrcmtMilicianos" value
 * @method SrcmtActividadIcmMiliciano setId()                  Sets the current record's "id" value
 * @method SrcmtActividadIcmMiliciano setCodigoMiliciano()     Sets the current record's "codigo_miliciano" value
 * @method SrcmtActividadIcmMiliciano setCodigoActividad()     Sets the current record's "codigo_actividad" value
 * @method SrcmtActividadIcmMiliciano setSrcmtActividadesIcm() Sets the current record's "SrcmtActividadesIcm" value
 * @method SrcmtActividadIcmMiliciano setSrcmtMilicianos()     Sets the current record's "SrcmtMilicianos" value
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtActividadIcmMiliciano extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_actividad_icm_miliciano');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_actividad_icm_miliciano_id',
             'length' => 4,
             ));
        $this->hasColumn('codigo_miliciano', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_actividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SrcmtActividadesIcm', array(
             'local' => 'codigo_actividad',
             'foreign' => 'codigo_actividad_icm'));

        $this->hasOne('SrcmtMilicianos', array(
             'local' => 'codigo_miliciano',
             'foreign' => 'codigo_miliciano'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}