<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SrcmtMilicianos', 'doctrine');

/**
 * BaseSrcmtMilicianos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_miliciano
 * @property enum $nacionalidad
 * @property integer $cedula_identidad
 * @property string $primer_apellido
 * @property string $segundo_apellido
 * @property string $primer_nombre
 * @property string $segundo_nombre
 * @property enum $sexo
 * @property date $fecha_nacimiento
 * @property enum $estado_civil
 * @property string $foto
 * @property enum $grupo_sanguineo
 * @property integer $codigo_estado
 * @property integer $codigo_municipio
 * @property integer $codigo_parroquia
 * @property integer $codigo_ciudad
 * @property string $direccion
 * @property string $telefono_local
 * @property string $movil
 * @property string $correo_electronico
 * @property string $direccion_emergencia
 * @property string $telefono_emergencia
 * @property enum $grado_instruccion
 * @property string $especialidad
 * @property string $idiomas
 * @property enum $nivel_dominio_idioma
 * @property integer $programa_formacion_grado
 * @property enum $trayecto
 * @property enum $tramo
 * @property string $aldea
 * @property integer $sedes
 * @property string $componente
 * @property string $jerarquia
 * @property string $contingente
 * @property string $arma_servicio
 * @property string $batallon_unidad_origen
 * @property string $profesion
 * @property string $oficio
 * @property boolean $trabaja_si_no
 * @property string $nombre_empresa
 * @property string $direccion_oficina
 * @property string $telefono_oficina
 * @property boolean $posee_vehiculo
 * @property string $tipo_vehiculo
 * @property string $modelo_vehiculo
 * @property string $numero_placa
 * @property boolean $posee_licencia
 * @property string $grado_licencia
 * @property boolean $porte_armas
 * @property string $numero_porte_armas
 * @property string $tipo_armamento
 * @property string $calibre_armamento
 * @property string $signos_particulares
 * @property enum $talla_uniforme
 * @property string $talla_calzado
 * @property string $estatura
 * @property float $peso
 * @property string $color_cabello
 * @property string $color_piel
 * @property string $discapacidad
 * @property string $alergias
 * @property enum $dominio_mano
 * @property boolean $practica_deporte
 * @property string $deporte
 * @property boolean $participa_actividad_cultural
 * @property string $actividad_cultural
 * @property string $agrupacion_social
 * @property string $misiones
 * @property string $cooperativas
 * @property string $apellidos_beneficiario
 * @property string $nombres_beneficiario
 * @property string $cedula_beneficiario
 * @property string $telefono_beneficiario
 * @property SrcmtPfg $SrcmtPfg
 * @property SrcmtSedes $SrcmtSedes
 * @property Doctrine_Collection $actividad_academica
 * @property Doctrine_Collection $actividad_icm
 * @property Doctrine_Collection $SrcmtActividadAcademicaMiliciano
 * @property Doctrine_Collection $SrcmtActividadIcmMiliciano
 * 
 * @method integer             getCodigoMiliciano()                  Returns the current record's "codigo_miliciano" value
 * @method enum                getNacionalidad()                     Returns the current record's "nacionalidad" value
 * @method integer             getCedulaIdentidad()                  Returns the current record's "cedula_identidad" value
 * @method string              getPrimerApellido()                   Returns the current record's "primer_apellido" value
 * @method string              getSegundoApellido()                  Returns the current record's "segundo_apellido" value
 * @method string              getPrimerNombre()                     Returns the current record's "primer_nombre" value
 * @method string              getSegundoNombre()                    Returns the current record's "segundo_nombre" value
 * @method enum                getSexo()                             Returns the current record's "sexo" value
 * @method date                getFechaNacimiento()                  Returns the current record's "fecha_nacimiento" value
 * @method enum                getEstadoCivil()                      Returns the current record's "estado_civil" value
 * @method string              getFoto()                             Returns the current record's "foto" value
 * @method enum                getGrupoSanguineo()                   Returns the current record's "grupo_sanguineo" value
 * @method integer             getCodigoEstado()                     Returns the current record's "codigo_estado" value
 * @method integer             getCodigoMunicipio()                  Returns the current record's "codigo_municipio" value
 * @method integer             getCodigoParroquia()                  Returns the current record's "codigo_parroquia" value
 * @method integer             getCodigoCiudad()                     Returns the current record's "codigo_ciudad" value
 * @method string              getDireccion()                        Returns the current record's "direccion" value
 * @method string              getTelefonoLocal()                    Returns the current record's "telefono_local" value
 * @method string              getMovil()                            Returns the current record's "movil" value
 * @method string              getCorreoElectronico()                Returns the current record's "correo_electronico" value
 * @method string              getDireccionEmergencia()              Returns the current record's "direccion_emergencia" value
 * @method string              getTelefonoEmergencia()               Returns the current record's "telefono_emergencia" value
 * @method enum                getGradoInstruccion()                 Returns the current record's "grado_instruccion" value
 * @method string              getEspecialidad()                     Returns the current record's "especialidad" value
 * @method string              getIdiomas()                          Returns the current record's "idiomas" value
 * @method enum                getNivelDominioIdioma()               Returns the current record's "nivel_dominio_idioma" value
 * @method integer             getProgramaFormacionGrado()           Returns the current record's "programa_formacion_grado" value
 * @method enum                getTrayecto()                         Returns the current record's "trayecto" value
 * @method enum                getTramo()                            Returns the current record's "tramo" value
 * @method string              getAldea()                            Returns the current record's "aldea" value
 * @method integer             getSedes()                            Returns the current record's "sedes" value
 * @method string              getComponente()                       Returns the current record's "componente" value
 * @method string              getJerarquia()                        Returns the current record's "jerarquia" value
 * @method string              getContingente()                      Returns the current record's "contingente" value
 * @method string              getArmaServicio()                     Returns the current record's "arma_servicio" value
 * @method string              getBatallonUnidadOrigen()             Returns the current record's "batallon_unidad_origen" value
 * @method string              getProfesion()                        Returns the current record's "profesion" value
 * @method string              getOficio()                           Returns the current record's "oficio" value
 * @method boolean             getTrabajaSiNo()                      Returns the current record's "trabaja_si_no" value
 * @method string              getNombreEmpresa()                    Returns the current record's "nombre_empresa" value
 * @method string              getDireccionOficina()                 Returns the current record's "direccion_oficina" value
 * @method string              getTelefonoOficina()                  Returns the current record's "telefono_oficina" value
 * @method boolean             getPoseeVehiculo()                    Returns the current record's "posee_vehiculo" value
 * @method string              getTipoVehiculo()                     Returns the current record's "tipo_vehiculo" value
 * @method string              getModeloVehiculo()                   Returns the current record's "modelo_vehiculo" value
 * @method string              getNumeroPlaca()                      Returns the current record's "numero_placa" value
 * @method boolean             getPoseeLicencia()                    Returns the current record's "posee_licencia" value
 * @method string              getGradoLicencia()                    Returns the current record's "grado_licencia" value
 * @method boolean             getPorteArmas()                       Returns the current record's "porte_armas" value
 * @method string              getNumeroPorteArmas()                 Returns the current record's "numero_porte_armas" value
 * @method string              getTipoArmamento()                    Returns the current record's "tipo_armamento" value
 * @method string              getCalibreArmamento()                 Returns the current record's "calibre_armamento" value
 * @method string              getSignosParticulares()               Returns the current record's "signos_particulares" value
 * @method enum                getTallaUniforme()                    Returns the current record's "talla_uniforme" value
 * @method string              getTallaCalzado()                     Returns the current record's "talla_calzado" value
 * @method string              getEstatura()                         Returns the current record's "estatura" value
 * @method float               getPeso()                             Returns the current record's "peso" value
 * @method string              getColorCabello()                     Returns the current record's "color_cabello" value
 * @method string              getColorPiel()                        Returns the current record's "color_piel" value
 * @method string              getDiscapacidad()                     Returns the current record's "discapacidad" value
 * @method string              getAlergias()                         Returns the current record's "alergias" value
 * @method enum                getDominioMano()                      Returns the current record's "dominio_mano" value
 * @method boolean             getPracticaDeporte()                  Returns the current record's "practica_deporte" value
 * @method string              getDeporte()                          Returns the current record's "deporte" value
 * @method boolean             getParticipaActividadCultural()       Returns the current record's "participa_actividad_cultural" value
 * @method string              getActividadCultural()                Returns the current record's "actividad_cultural" value
 * @method string              getAgrupacionSocial()                 Returns the current record's "agrupacion_social" value
 * @method string              getMisiones()                         Returns the current record's "misiones" value
 * @method string              getCooperativas()                     Returns the current record's "cooperativas" value
 * @method string              getApellidosBeneficiario()            Returns the current record's "apellidos_beneficiario" value
 * @method string              getNombresBeneficiario()              Returns the current record's "nombres_beneficiario" value
 * @method string              getCedulaBeneficiario()               Returns the current record's "cedula_beneficiario" value
 * @method string              getTelefonoBeneficiario()             Returns the current record's "telefono_beneficiario" value
 * @method SrcmtPfg            getSrcmtPfg()                         Returns the current record's "SrcmtPfg" value
 * @method SrcmtSedes          getSrcmtSedes()                       Returns the current record's "SrcmtSedes" value
 * @method Doctrine_Collection getActividadAcademica()               Returns the current record's "actividad_academica" collection
 * @method Doctrine_Collection getActividadIcm()                     Returns the current record's "actividad_icm" collection
 * @method Doctrine_Collection getSrcmtActividadAcademicaMiliciano() Returns the current record's "SrcmtActividadAcademicaMiliciano" collection
 * @method Doctrine_Collection getSrcmtActividadIcmMiliciano()       Returns the current record's "SrcmtActividadIcmMiliciano" collection
 * @method SrcmtMilicianos     setCodigoMiliciano()                  Sets the current record's "codigo_miliciano" value
 * @method SrcmtMilicianos     setNacionalidad()                     Sets the current record's "nacionalidad" value
 * @method SrcmtMilicianos     setCedulaIdentidad()                  Sets the current record's "cedula_identidad" value
 * @method SrcmtMilicianos     setPrimerApellido()                   Sets the current record's "primer_apellido" value
 * @method SrcmtMilicianos     setSegundoApellido()                  Sets the current record's "segundo_apellido" value
 * @method SrcmtMilicianos     setPrimerNombre()                     Sets the current record's "primer_nombre" value
 * @method SrcmtMilicianos     setSegundoNombre()                    Sets the current record's "segundo_nombre" value
 * @method SrcmtMilicianos     setSexo()                             Sets the current record's "sexo" value
 * @method SrcmtMilicianos     setFechaNacimiento()                  Sets the current record's "fecha_nacimiento" value
 * @method SrcmtMilicianos     setEstadoCivil()                      Sets the current record's "estado_civil" value
 * @method SrcmtMilicianos     setFoto()                             Sets the current record's "foto" value
 * @method SrcmtMilicianos     setGrupoSanguineo()                   Sets the current record's "grupo_sanguineo" value
 * @method SrcmtMilicianos     setCodigoEstado()                     Sets the current record's "codigo_estado" value
 * @method SrcmtMilicianos     setCodigoMunicipio()                  Sets the current record's "codigo_municipio" value
 * @method SrcmtMilicianos     setCodigoParroquia()                  Sets the current record's "codigo_parroquia" value
 * @method SrcmtMilicianos     setCodigoCiudad()                     Sets the current record's "codigo_ciudad" value
 * @method SrcmtMilicianos     setDireccion()                        Sets the current record's "direccion" value
 * @method SrcmtMilicianos     setTelefonoLocal()                    Sets the current record's "telefono_local" value
 * @method SrcmtMilicianos     setMovil()                            Sets the current record's "movil" value
 * @method SrcmtMilicianos     setCorreoElectronico()                Sets the current record's "correo_electronico" value
 * @method SrcmtMilicianos     setDireccionEmergencia()              Sets the current record's "direccion_emergencia" value
 * @method SrcmtMilicianos     setTelefonoEmergencia()               Sets the current record's "telefono_emergencia" value
 * @method SrcmtMilicianos     setGradoInstruccion()                 Sets the current record's "grado_instruccion" value
 * @method SrcmtMilicianos     setEspecialidad()                     Sets the current record's "especialidad" value
 * @method SrcmtMilicianos     setIdiomas()                          Sets the current record's "idiomas" value
 * @method SrcmtMilicianos     setNivelDominioIdioma()               Sets the current record's "nivel_dominio_idioma" value
 * @method SrcmtMilicianos     setProgramaFormacionGrado()           Sets the current record's "programa_formacion_grado" value
 * @method SrcmtMilicianos     setTrayecto()                         Sets the current record's "trayecto" value
 * @method SrcmtMilicianos     setTramo()                            Sets the current record's "tramo" value
 * @method SrcmtMilicianos     setAldea()                            Sets the current record's "aldea" value
 * @method SrcmtMilicianos     setSedes()                            Sets the current record's "sedes" value
 * @method SrcmtMilicianos     setComponente()                       Sets the current record's "componente" value
 * @method SrcmtMilicianos     setJerarquia()                        Sets the current record's "jerarquia" value
 * @method SrcmtMilicianos     setContingente()                      Sets the current record's "contingente" value
 * @method SrcmtMilicianos     setArmaServicio()                     Sets the current record's "arma_servicio" value
 * @method SrcmtMilicianos     setBatallonUnidadOrigen()             Sets the current record's "batallon_unidad_origen" value
 * @method SrcmtMilicianos     setProfesion()                        Sets the current record's "profesion" value
 * @method SrcmtMilicianos     setOficio()                           Sets the current record's "oficio" value
 * @method SrcmtMilicianos     setTrabajaSiNo()                      Sets the current record's "trabaja_si_no" value
 * @method SrcmtMilicianos     setNombreEmpresa()                    Sets the current record's "nombre_empresa" value
 * @method SrcmtMilicianos     setDireccionOficina()                 Sets the current record's "direccion_oficina" value
 * @method SrcmtMilicianos     setTelefonoOficina()                  Sets the current record's "telefono_oficina" value
 * @method SrcmtMilicianos     setPoseeVehiculo()                    Sets the current record's "posee_vehiculo" value
 * @method SrcmtMilicianos     setTipoVehiculo()                     Sets the current record's "tipo_vehiculo" value
 * @method SrcmtMilicianos     setModeloVehiculo()                   Sets the current record's "modelo_vehiculo" value
 * @method SrcmtMilicianos     setNumeroPlaca()                      Sets the current record's "numero_placa" value
 * @method SrcmtMilicianos     setPoseeLicencia()                    Sets the current record's "posee_licencia" value
 * @method SrcmtMilicianos     setGradoLicencia()                    Sets the current record's "grado_licencia" value
 * @method SrcmtMilicianos     setPorteArmas()                       Sets the current record's "porte_armas" value
 * @method SrcmtMilicianos     setNumeroPorteArmas()                 Sets the current record's "numero_porte_armas" value
 * @method SrcmtMilicianos     setTipoArmamento()                    Sets the current record's "tipo_armamento" value
 * @method SrcmtMilicianos     setCalibreArmamento()                 Sets the current record's "calibre_armamento" value
 * @method SrcmtMilicianos     setSignosParticulares()               Sets the current record's "signos_particulares" value
 * @method SrcmtMilicianos     setTallaUniforme()                    Sets the current record's "talla_uniforme" value
 * @method SrcmtMilicianos     setTallaCalzado()                     Sets the current record's "talla_calzado" value
 * @method SrcmtMilicianos     setEstatura()                         Sets the current record's "estatura" value
 * @method SrcmtMilicianos     setPeso()                             Sets the current record's "peso" value
 * @method SrcmtMilicianos     setColorCabello()                     Sets the current record's "color_cabello" value
 * @method SrcmtMilicianos     setColorPiel()                        Sets the current record's "color_piel" value
 * @method SrcmtMilicianos     setDiscapacidad()                     Sets the current record's "discapacidad" value
 * @method SrcmtMilicianos     setAlergias()                         Sets the current record's "alergias" value
 * @method SrcmtMilicianos     setDominioMano()                      Sets the current record's "dominio_mano" value
 * @method SrcmtMilicianos     setPracticaDeporte()                  Sets the current record's "practica_deporte" value
 * @method SrcmtMilicianos     setDeporte()                          Sets the current record's "deporte" value
 * @method SrcmtMilicianos     setParticipaActividadCultural()       Sets the current record's "participa_actividad_cultural" value
 * @method SrcmtMilicianos     setActividadCultural()                Sets the current record's "actividad_cultural" value
 * @method SrcmtMilicianos     setAgrupacionSocial()                 Sets the current record's "agrupacion_social" value
 * @method SrcmtMilicianos     setMisiones()                         Sets the current record's "misiones" value
 * @method SrcmtMilicianos     setCooperativas()                     Sets the current record's "cooperativas" value
 * @method SrcmtMilicianos     setApellidosBeneficiario()            Sets the current record's "apellidos_beneficiario" value
 * @method SrcmtMilicianos     setNombresBeneficiario()              Sets the current record's "nombres_beneficiario" value
 * @method SrcmtMilicianos     setCedulaBeneficiario()               Sets the current record's "cedula_beneficiario" value
 * @method SrcmtMilicianos     setTelefonoBeneficiario()             Sets the current record's "telefono_beneficiario" value
 * @method SrcmtMilicianos     setSrcmtPfg()                         Sets the current record's "SrcmtPfg" value
 * @method SrcmtMilicianos     setSrcmtSedes()                       Sets the current record's "SrcmtSedes" value
 * @method SrcmtMilicianos     setActividadAcademica()               Sets the current record's "actividad_academica" collection
 * @method SrcmtMilicianos     setActividadIcm()                     Sets the current record's "actividad_icm" collection
 * @method SrcmtMilicianos     setSrcmtActividadAcademicaMiliciano() Sets the current record's "SrcmtActividadAcademicaMiliciano" collection
 * @method SrcmtMilicianos     setSrcmtActividadIcmMiliciano()       Sets the current record's "SrcmtActividadIcmMiliciano" collection
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Oswaldo Zarraga
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSrcmtMilicianos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('srcmt_milicianos');
        $this->hasColumn('codigo_miliciano', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'srcmt_milicianos_codigo_miliciano',
             'length' => 4,
             ));
        $this->hasColumn('nacionalidad', 'enum', 1, array(
             'type' => 'enum',
             'length' => 1,
             'values' => 
             array(
              0 => 'V',
              1 => 'E',
             ),
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('cedula_identidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'unique' => true,
             'length' => 4,
             ));
        $this->hasColumn('primer_apellido', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('segundo_apellido', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('primer_nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('segundo_nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('sexo', 'enum', 1, array(
             'type' => 'enum',
             'length' => 1,
             'values' => 
             array(
              0 => 'F',
              1 => 'M',
             ),
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('estado_civil', 'enum', 11, array(
             'type' => 'enum',
             'length' => 11,
             'values' => 
             array(
              0 => 'SOLTERO',
              1 => 'CASADO',
              2 => 'DIVORCIADO',
              3 => 'VIUDO',
              4 => 'CONCUBINATO',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('foto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('grupo_sanguineo', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'O+',
              1 => 'O-',
              2 => 'A-',
              3 => 'A+',
              4 => 'B-',
              5 => 'B+',
              6 => 'AB-',
              7 => 'AB+',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('codigo_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_municipio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_parroquia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_ciudad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_local', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('movil', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('correo_electronico', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('direccion_emergencia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_emergencia', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('grado_instruccion', 'enum', 14, array(
             'type' => 'enum',
             'length' => 14,
             'values' => 
             array(
              0 => '',
              1 => 'Basico',
              2 => 'Medio',
              3 => 'Diversificado',
              4 => 'Universitario',
              5 => 'Posgrado',
              6 => 'Doctorado',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('especialidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('idiomas', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('nivel_dominio_idioma', 'enum', 8, array(
             'type' => 'enum',
             'length' => 8,
             'values' => 
             array(
              0 => 'Basico',
              1 => 'Avanzado',
             ),
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('programa_formacion_grado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('trayecto', 'enum', 3, array(
             'type' => 'enum',
             'length' => 3,
             'values' => 
             array(
              0 => '',
              1 => 'I',
              2 => 'II',
              3 => 'III',
              4 => 'IV',
             ),
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('tramo', 'enum', 3, array(
             'type' => 'enum',
             'length' => 3,
             'values' => 
             array(
              0 => '',
              1 => 'I',
              2 => 'II',
              3 => 'III',
             ),
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('aldea', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sedes', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('componente', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('jerarquia', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('contingente', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('arma_servicio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('batallon_unidad_origen', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('profesion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('oficio', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('trabaja_si_no', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('nombre_empresa', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('direccion_oficina', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_oficina', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('posee_vehiculo', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('tipo_vehiculo', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('modelo_vehiculo', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('numero_placa', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('posee_licencia', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('grado_licencia', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 5,
             ));
        $this->hasColumn('porte_armas', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('numero_porte_armas', 'string', 15, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('tipo_armamento', 'string', 11, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 11,
             ));
        $this->hasColumn('calibre_armamento', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 5,
             ));
        $this->hasColumn('signos_particulares', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('talla_uniforme', 'enum', 3, array(
             'type' => 'enum',
             'length' => 3,
             'values' => 
             array(
              0 => '',
              1 => 'SS',
              2 => 'SL',
              3 => 'SR',
              4 => 'MR',
              5 => 'ML',
              6 => 'LL',
              7 => 'LM',
              8 => 'LR',
              9 => 'XL',
              10 => 'XXL',
             ),
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('talla_calzado', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('estatura', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('peso', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('color_cabello', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 10,
             ));
        $this->hasColumn('color_piel', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('discapacidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('alergias', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('dominio_mano', 'enum', 15, array(
             'type' => 'enum',
             'length' => 15,
             'values' => 
             array(
              0 => '',
              1 => 'Diestro',
              2 => 'Siniestro',
              3 => 'Ambidiestro',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('practica_deporte', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('deporte', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('participa_actividad_cultural', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('actividad_cultural', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('agrupacion_social', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('misiones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cooperativas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellidos_beneficiario', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 60,
             ));
        $this->hasColumn('nombres_beneficiario', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 60,
             ));
        $this->hasColumn('cedula_beneficiario', 'string', 11, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 11,
             ));
        $this->hasColumn('telefono_beneficiario', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SrcmtPfg', array(
             'local' => 'programa_formacion_grado',
             'foreign' => 'id_pfg'));

        $this->hasOne('SrcmtSedes', array(
             'local' => 'sedes',
             'foreign' => 'id_sedes'));

        $this->hasMany('SrcmtActividadesAcademicas as actividad_academica', array(
             'refClass' => 'SrcmtActividadAcademicaMiliciano',
             'local' => 'codigo_miliciano',
             'foreign' => 'codigo_actividad_academica'));

        $this->hasMany('SrcmtActividadesIcm as actividad_icm', array(
             'refClass' => 'SrcmtActividadIcmMiliciano',
             'local' => 'codigo_miliciano',
             'foreign' => 'codigo_actividad'));

        $this->hasMany('SrcmtActividadAcademicaMiliciano', array(
             'local' => 'codigo_miliciano',
             'foreign' => 'codigo_miliciano'));

        $this->hasMany('SrcmtActividadIcmMiliciano', array(
             'local' => 'codigo_miliciano',
             'foreign' => 'codigo_miliciano'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}