<?php

/**
 * SrcmtEstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtEstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtEstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtEstado');
    }
}