<?php

/**
 * SrcmtActividadesIcm
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    srcmt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SrcmtActividadesIcm extends BaseSrcmtActividadesIcm {

	public function getFechaFormateado() {
		return $this->getDateTimeObject('fecha')->format('d-m-Y');
	}

	public function getCreatedAtFormateado() {
		return $this->getDateTimeObject('created_at')->format('d-m-Y H:i');
	}

	public function getUpdatedAtFormateado() {
		return $this->getDateTimeObject('updated_at')->format('d-m-Y H:i');
	}

	public function __toString() {

		parent::__toString();


		return $this->getSrcmtTipoActividad() . ": " . $this->getActividad() . " " . $this->getFechaFormateado();
	}

	public static function getArregloTitulosCampos() {
		$ArregloTitulosCampos = Array(
		    'C&oacute;digo Actividad' => 'codigo_actividad_icm',
		    'Tipo de Actividad' => 'codigo_tipo_actividad',
		    'Actividad' => 'actividad',
		    'Responsable' => 'responsable',
		    'Fecha' => 'fecha',
		    'Lugar' => 'lugar',
		    'Duraci&oacute;n' => 'duracion',
		    'Descripci&oacute;n' => 'descripcion',
		    'Fecha de Creaci&oacute;n' => 'created_at',
		    'Fecha de Actualizaci&oacute;n' => 'updated_at'
		);
		return $ArregloTitulosCampos;
	}

}