<?php

/**
 * SrcmtActividadAcademicaBrigadistaDadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtActividadAcademicaBrigadistaDadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtActividadAcademicaBrigadistaDadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtActividadAcademicaBrigadistaDado');
    }
}