<?php

/**
 * SrcmtSedesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtSedesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtSedesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtSedes');
    }
}