<?php

/**
 * SrcmtSedes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    srcmt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SrcmtSedes extends BaseSrcmtSedes {

    public function getSlug() {
        return Srcmt::slugify($this->getSedes());
    }

    public function __toString() {
        return parent::getSedes();
    }

}