<?php

/**
 * SrcmtTipoActividadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtTipoActividadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtTipoActividadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtTipoActividad');
    }
}