<?php

/**
 * SrcmtParroquiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtParroquiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtParroquiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtParroquia');
    }
}