<?php

/**
 * SrcmtMilicianosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtMilicianosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtMilicianosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtMilicianos');
    }
}