<?php

/**
 * SrcmtActividadIcmBrigadistaDadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtActividadIcmBrigadistaDadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtActividadIcmBrigadistaDadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtActividadIcmBrigadistaDado');
    }
}