<?php

/**
 * SrcmtActividadAcademicaMilicianoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtActividadAcademicaMilicianoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtActividadAcademicaMilicianoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtActividadAcademicaMiliciano');
    }
}