<?php

/**
 * SrcmtActividadesIcmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtActividadesIcmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtActividadesIcmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtActividadesIcm');
    }
}