<?php

/**
 * SrcmtBrigadistasDado
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    srcmt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SrcmtBrigadistasDado extends BaseSrcmtBrigadistasDado {

	public static function getTitulosCampos() {
		$titulosCampos = Array(
		    'C&oacute;digo Brigadista',
		    'Nacionalidad',
		    'C&eacute;dula Identidad',
		    'Religi&oacute;n',
		    'Primer Apellido',
		    'Segundo Apellido',
		    'Primer Nombre',
		    'Segundo Nombre',
		    'Sexo',
		    'Fecha de Nacimiento',
		    'Lugar de Nacimiento',
		    'Estado Civil',
		    'Grupo Sangu&iacute;neo',
		    'Estado',
		    'Municipio',
		    'Parroquia',
		    'Ciudad',
		    'Direcci&oacute;n Domiciliaria',
		    'Tel&eacute;fono de Domicilio',
		    'Tel&eacute;fono Movil',
		    'Correo Electr&oacute;nico',
		    'Direcci&oacute;n Emergencia',
		    'Tel&eacute;fono Emergencia',
		    'Unidad Adscripci&oacute;n Laboral',
		    'Extensi&oacute;n interna',
		    'Perfil Empleado',
		    'Jefe Sector',
		    'Grado Instruccion',
		    'Especialidad',
		    'Sedes',
		    'Jerarquia',
		    'Profesion',
		    'Oficio',
		    'Centro Votacion Cne',
		    'Direcci&oacute;n Oficina',
		    'Talla Pantal&oacute;n',
		    'Talla/Camisa',
		    'Talla/Calzado',
		    'Talla/Gorra',
		    'Estatura',
		    'Peso',
		    'Color de Cabello',
		    'Color de Piel',
		    'Discapacidad',
		    'Alergias',
		    'Dominio de la Mano',
		    'Deporte',
		    'Actividades Culturales',
		    'Apellidos del Beneficiario',
		    'Nombres del Beneficiario',
		    'C&eacute;dula Beneficiario',
		    'Tel&eacute;fono Beneficiario',
		    'Fecha de Creaci&oacute;n',
		    'Fecha de Actualizaci&oacute;n'
		);
		return $titulosCampos;
	}

	public static function getArregloTitulosCampos() {
		$ArregloTitulosCampos = Array(
		    'C&oacute;digo Brigadista'=>'codigo_brigadista',
		    'Nacionalidad'=>'nacionalidad',
		    'C&eacute;dula Identidad'=>'cedula_identidad',
		    'Religi&oacute;n'=>'religion',
		    'Primer Apellido'=>'primer_apellido',
		    'Segundo Apellido'=>'segundo_apellido',
		    'Primer Nombre'=>'primer_nombre',
		    'Segundo Nombre'=>'segundo_nombre',
		    'Sexo'=>'sexo',
		    'Fecha de Nacimiento'=>'fecha_nacimiento',
		    'Lugar de Nacimiento'=>'lugar_de_nacimiento',
		    'Estado Civil'=>'estado_civil',
		    'Grupo Sangu&iacute;neo'=>'grupo_sanguineo',
		    'Estado'=>'codigo_estado',
		    'Municipio'=>'codigo_municipio',
		    'Parroquia'=>'codigo_parroquia',
		    'Ciudad'=>'codigo_ciudad',
		    'Direcci&oacute;n Domiciliaria'=>'direccion_domiciliaria',
		    'Tel&eacute;fono de Domicilio'=>'telefono_domicilio',
		    'Tel&eacute;fono Movil'=>'telefono_movil',
		    'Correo Electr&oacute;nico'=>'correo_electronico',
		    'Direcci&oacute;n Emergencia'=>'direccion_emergencia',
		    'Tel&eacute;fono Emergencia'=>'telefono_emergencia',
		    'Unidad Adscripci&oacute;n Laboral'=>'unidad_adscripcion_laboral',
		    'Extensi&oacute;n interna'=>'extension_interna',
		    'Perfil Empleado'=>'perfil_empleado',
		    'Jefe Sector'=>'jefe_sector',
		    'Grado Instruccion'=>'grado_instruccion',
		    'Especialidad'=>'especialidad',
		    'Sedes'=>'sedes',
		    'Jerarquia'=>'jerarquia',
		    'Profesion'=>'profesion',
		    'Oficio'=>'oficio',
		    'Centro Votacion Cne'=>'centro_votacion_cne',
		    'Direcci&oacute;n Oficina'=>'direccion_oficina',
		    'Talla Pantal&oacute;n'=>'talla_pantalon',
		    'Talla/Camisa'=>'talla_camisa',
		    'Talla/Calzado'=>'talla_calzado',
		    'Talla/Gorra'=>'talla_gorra',
		    'Estatura'=>'estatura',
		    'Peso'=>'peso',
		    'Color de Cabello'=>'color_cabello',
		    'Color de Piel'=>'color_piel',
		    'Discapacidad'=>'discapacidad',
		    'Alergias'=>'alergias',
		    'Dominio de la Mano'=>'dominio_mano',
		    'Deporte'=>'deporte',
		    'Actividades Culturales'=>'actividades_culturales',
		    'Apellidos del Beneficiario'=>'apellidos_beneficiario',
		    'Nombres del Beneficiario'=>'nombres_beneficiario',
		    'C&eacute;dula Beneficiario'=>'cedula_beneficiario',
		    'Tel&eacute;fono Beneficiario'=>'telefono_beneficiario',
		    'Fecha de Creaci&oacute;n'=>'created_at',
		    'Fecha de Actualizaci&oacute;n'=>'updated_at'
		);
		return $ArregloTitulosCampos;
	}
	public static function getArregloTitulosCamposParaPdf() {
		$ArregloTitulosCampos = Array(
		    'C\ódigo Brigadista'=>'codigo_brigadista',
		    'Nacionalidad'=>'nacionalidad',
		    'Cédula Identidad'=>'cedula_identidad',
		    'Religión'=>'religion',
		    'Primer Apellido'=>'primer_apellido',
		    'Segundo Apellido'=>'segundo_apellido',
		    'Primer Nombre'=>'primer_nombre',
		    'Segundo Nombre'=>'segundo_nombre',
		    'Sexo'=>'sexo',
		    'Fecha de Nacimiento'=>'fecha_nacimiento',
		    'Lugar de Nacimiento'=>'lugar_de_nacimiento',
		    'Estado Civil'=>'estado_civil',
		    'Grupo Sanguíneo'=>'grupo_sanguineo',
		    'Estado'=>'codigo_estado',
		    'Municipio'=>'codigo_municipio',
		    'Parroquia'=>'codigo_parroquia',
		    'Ciudad'=>'codigo_ciudad',
		    'Dirección Domiciliaria'=>'direccion_domiciliaria',
		    'Teléfono de Domicilio'=>'telefono_domicilio',
		    'Teléfono Movil'=>'telefono_movil',
		    'Correo Electrónico'=>'correo_electronico',
		    'Dirección Emergencia'=>'direccion_emergencia',
		    'Teléfono Emergencia'=>'telefono_emergencia',
		    'Unidad Adscripción Laboral'=>'unidad_adscripcion_laboral',
		    'Extensión interna'=>'extension_interna',
		    'Perfil Empleado'=>'perfil_empleado',
		    'Jefe Sector'=>'jefe_sector',
		    'Grado Instrucción'=>'grado_instruccion',
		    'Especialidad'=>'especialidad',
		    'Sedes'=>'sedes',
		    'Jerarquia'=>'jerarquia',
		    'Profesión'=>'profesion',
		    'Oficio'=>'oficio',
		    'Centro Votación Cne'=>'centro_votacion_cne',
		    'Dirección Oficina'=>'direccion_oficina',
		    'Talla Pantalón'=>'talla_pantalon',
		    'Talla/Camisa'=>'talla_camisa',
		    'Talla/Calzado'=>'talla_calzado',
		    'Talla/Gorra'=>'talla_gorra',
		    'Estatura'=>'estatura',
		    'Peso'=>'peso',
		    'Color de Cabello'=>'color_cabello',
		    'Color de Piel'=>'color_piel',
		    'Discapacidad'=>'discapacidad',
		    'Alergias'=>'alergias',
		    'Dominio de la Mano'=>'dominio_mano',
		    'Deporte'=>'deporte',
		    'Actividades Culturales'=>'actividades_culturales',
		    'Apellidos del Beneficiario'=>'apellidos_beneficiario',
		    'Nombres del Beneficiario'=>'nombres_beneficiario',
		    'C&eacute;dula Beneficiario'=>'cedula_beneficiario',
		    'Teléfono Beneficiario'=>'telefono_beneficiario',
		    'Fecha de Creación'=>'created_at',
		    'Fecha de Actualización'=>'updated_at'
		);
		return $ArregloTitulosCampos;
	}

        public function getCedulaIdentidadFormateada() {
            return number_format($this->getCedulaIdentidad(), 0, ',', '.');
            
        }
        public function getEstado() {
		$Estado = Doctrine::getTable('SrcmtEstado')
			->createQuery('a')
			->where('a.codigo_estado=?', array($this->getCodigoEstado()))
			->limit(1)
			->execute();
		if ($Estado->count() <= 0) {
			$nombreEstado = '';
		} else {
			$nombreEstado = $Estado->getFirst()->getEstado();
		}

		return $nombreEstado;
	}

	public function getMunicipio() {
		$Municipio = Doctrine::getTable('SrcmtMunicipio')
			->createQuery('a')
			->where('a.codigo_estado=?', array(parent::getCodigoEstado()))
			->andWhere('a.codigo_municipio=?', array(parent::getCodigoMunicipio()))
			->limit(1)
			->execute();

		if ($Municipio->count() <= 0) {
			$nombreMunicipio = '';
		} else {
			$nombreMunicipio = $Municipio->getFirst()->getMunicipio();
		}
		return $nombreMunicipio;
	}

	public function getParroquia() {
		$Parroquia = Doctrine::getTable('SrcmtParroquia')
			->createQuery('a')
			->where('a.codigo_estado=?', array(parent::getCodigoEstado()))
			->andWhere('a.codigo_municipio=?', array(parent::getCodigoMunicipio()))
			->andWhere('a.codigo_parroquia=?', array(parent::getCodigoParroquia()))
			->limit(1)
			->execute();
		if ($Parroquia->count() <= 0) {
			$nombreParroquia = '';
		} else {
			$nombreParroquia = $Parroquia->getFirst()->getParroquia();
		}
		return $nombreParroquia;
	}

	public function getCiudad() {
		$Ciudad = Doctrine::getTable('SrcmtCiudad')
			->createQuery('a')
			->where('a.codigo_estado=?', array(parent::getCodigoEstado()))
			->andWhere('a.codigo_municipio=?', array(parent::getCodigoMunicipio()))
			->andWhere('a.codigo_Ciudad=?', array(parent::getCodigoCiudad()))
			->limit(1)
			->execute();

		if ($Ciudad->count() <= 0) {
			$nombreCiudad = '';
		} else {
			$nombreCiudad = $Ciudad->getFirst()->getCiudad();
		}
		return $nombreCiudad;
	}
	public function __toString() {
		return parent::getNacionalidad() . '-' .
			parent::getCedulaIdentidad() . ' ' .
			parent::getPrimerApellido() . ' ' .
			parent::getPrimerNombre()
		;
	}
	public function getFechaNacimientoFormateado() {
		return $this->getDateTimeObject('fecha_nacimiento')->format('d-m-Y');
	}

	public function getCreatedAtFormateado() {
		return $this->getDateTimeObject('created_at')->format('d-m-Y H:i');
	}

	public function getUpdatedAtFormateado() {
		return $this->getDateTimeObject('updated_at')->format('d-m-Y H:i');
	}



}