<?php

/**
 * SrcmtMunicipioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtMunicipioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtMunicipioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtMunicipio');
    }
}