<?php

/**
 * SrcmtBrigadistasDadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SrcmtBrigadistasDadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SrcmtBrigadistasDadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SrcmtBrigadistasDado');
    }
}