sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               sfGuardGroup
    prefix_path:          /guard/grupos
    column:               id
    with_wildcard_routes: true

sf_guard_group_filter:
  url: /guard/grupos/filter
  class: sfDoctrineRoute
  options: { model: sfGuardGroup, type: list }
  params: { module: sfGuardGroup, action: filter }
  requirements:
    sf_method: [post]

sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               sfGuardPermission
    prefix_path:          /guard/permisos
    column:               id
    with_wildcard_routes: true

sf_guard_permission_filter:
  url: /guard/permisos/filter
  class: sfDoctrineRoute
  options: { model: sfGuardPermission, type: list }
  params: { module: sfGuardPermission, action: filter }
  requirements:
    sf_method: [post]

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sfGuardUser
    prefix_path:          /guard/usuarios
    column:               id
    with_wildcard_routes: true

sf_guard_user_filter:
  url: /guard/usuarios/filter
  class: sfDoctrineRoute
  options: { model: sfGuardUser, type: list }
  params: { module: sfGuardUser, action: filter }
  requirements:
    sf_method: [post]



srcmt_tipo_actividad:
  class: sfDoctrineRouteCollection
  options:
    model:                SrcmtTipoActividad
    module:               SrcmtTipoActividad
    prefix_path:          /Tipo/Actividades
    column:               codigo_tipo_actividad
    with_wildcard_routes: true

srcmt_sedes:
  class: sfDoctrineRouteCollection
  options:
    model:                SrcmtSedes
    module:               SrcmtSedes
    prefix_path:          /Sedes
    column:               id_sedes
    with_wildcard_routes: true

srcmt_pfg:
  class: sfDoctrineRouteCollection
  options:
    model:                SrcmtPfg
    module:               SrcmtPfg
    prefix_path:          /Pfg
    column:               id_pfg
    with_wildcard_routes: true

sf_guard_secure:
  url:   /guard/secure
  param: { module: sfGuardAuth, action: secure }


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
