<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/06/05 06:23:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;port=5432;dbname=srcmt',
  'username' => 'srcmt',
  'password' => 'srcmt',
  'name' => 'doctrine',
)),);
