<?php
// auto-generated by sfViewConfigHandler
// date: 2013/06/16 23:45:39
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array (  'media' => 'all',));
  $response->addStylesheet('ubv/jquery-ui-1.8.13.custom.css', '', array (  'media' => 'all',));
  $response->addStylesheet('srcmt.css', '', array (  'media' => 'all',));
  $response->addJavascript('jquery-1.5.1.min.js', '', array (  'media' => 'all',));
  $response->addJavascript('jquery-ui-1.8.13.custom.min.js', '', array (  'media' => 'all',));
  $response->addJavascript('jquery.ui.datepicker-es.js', '', array (  'media' => 'all',));
  $response->addJavascript('srcmt.js', '', array (  'media' => 'all',));


